### ISSUE TITLE
Shape edges are not smooth

### ISSUE THREAD

**Issue by LU347** [aryandutt/drawsome#5]
![image](https://github.com/aryandutt/drawsome/assets/103535661/d7eec582-1860-4bb7-a149-303163292069)

**Comment by aryandutt** [comment]
_It's not a bug, it's a feature!_

The randomness of the outlines of the shapes is controlled by a property called sloppiness which can be found in the property menu once you select a drawing tool. If you enable the first option then the shapes will turn out completely smooth.

I hope this clears it!

**Comment by aryandutt** [comment]
_It's not a bug, it's a feature!_

The randomness of the outlines of the shapes is controlled by a property called sloppiness which can be found in the property menu once you select a drawing tool. If you enable the first option then the shapes will turn out completely smooth.

I hope this clears it!

**Comment by LU347** [comment]
Sorry about that! 😅
