### ISSUE TITLE
Export Option

### ISSUE THREAD

**Issue by simi360** [aryandutt/drawsome#6]
Description:

Currently, Drawsome lacks the ability for users to export their creations directly from the application. This feature request aims to address this limitation by providing users with the option to export their drawings in various file formats.

Proposed Functionality:

- Implement a new menu or dialog box within Drawsome specifically for exporting drawings.
- Offer a range of commonly used file formats for export, such as PNG, JPEG, SVG, and PDF.
- Allow users to customize export settings, such as resolution and compression level, where applicable. (optional)
- Provide clear and intuitive guidance for users on how to access and use the export functionality.

Benefits:

- Empowers users to save and share their creations in formats suitable for their intended use
- Enhances the overall usability and utility of Drawsome, making it a more versatile tool for artists and designers.

**Comment by aryandutt** [comment]
Would you like to work on this issue?

**Comment by simi360** [comment]
Yes please

**Comment by aryandutt** [comment]
Cool, please feel free to contact me if you need any help.
